projects:
 - name: apps
   namespace: argocd
   additionalLabels: {}
   additionalAnnotations: {}
   finalizers:
   - resources-finalizer.argocd.argoproj.io
   description: Apps project
   sourceRepos:
   - '*'
   destinations:
   - namespace: argocd
     server: https://kubernetes.default.svc
 - name: child-apps
   namespace: argocd
   additionalLabels: {}
   additionalAnnotations: {}
   finalizers:
   - resources-finalizer.argocd.argoproj.io
   description: Child applications project
   sourceRepos:
   - '*'
   destinations:
   - namespace: child-apps
     server: https://kubernetes.default.svc